import type { RoomData, ObjectData } from '../types'
import { state, toast, isStateLocked, withStateLock, assetMap } from './state'
import { editorLog } from './log'
import { editorFloorLabelToFloorId } from './helpers'
import { EDITOR_CONFIG } from './migrate'

let saveDebounceTimer: number | null = null
let isSaving = false
let assetsSaveDebounceTimer: number | null = null
let isSavingAssets = false
const MAX_SAVE_RETRIES = 3

export async function saveLayout(): Promise<void> {
	if (isStateLocked()) return saveLayoutLocked()
	return withStateLock(saveLayoutLocked)
}

async function saveLayoutLocked(): Promise<void> {
	if (isSaving) {
		if (saveDebounceTimer) window.clearTimeout(saveDebounceTimer)
		saveDebounceTimer = window.setTimeout(() => saveLayout(), EDITOR_CONFIG.saveDebounceMs)
		return
	}

	isSaving = true
	let hasDebounced = false
	try {
		const data = state.layout
		const ts = `// Auto-generated by Blueprint Editor - ${new Date().toISOString()}
import type { FloorLayoutData } from '../types'

const SAVED_LAYOUT: FloorLayoutData = ${JSON.stringify(data)}
`

		const attemptSave = async (attempt: number): Promise<boolean> => {
			try {
				const res = await fetch(EDITOR_CONFIG.saveEndpoint, {
					method: 'POST',
					headers: { 'Content-Type': 'text/plain', 'X-Blueprint-Save': '1' },
					body: ts,
				})
				if (!res.ok) throw new Error(`HTTP ${res.status}`)
				return true
			} catch (e) {
				editorLog.error('saveLayout attempt ' + attempt, e)
				if (attempt < MAX_SAVE_RETRIES) {
					await new Promise(resolve => setTimeout(resolve, 1000 * (attempt + 1)))
					return attemptSave(attempt + 1)
				}
				return false
			}
		}

		const success = await attemptSave(1)
		if (!success) {
			editorLog.error('saveLayout', 'All retries failed')
			toast.error('Failed to save - falling back to download')
			const blob = new Blob([ts], { type: 'text/typescript' })
			const url = URL.createObjectURL(blob)
			const a = document.createElement('a')
			a.href = url
			a.download = 'blueprint-layout.ts'
			a.click()
			window.setTimeout(() => URL.revokeObjectURL(url), 1000)
		}
	} finally {
		isSaving = false
		if (saveDebounceTimer) {
			window.clearTimeout(saveDebounceTimer)
			saveDebounceTimer = null
			hasDebounced = true
		}
	}

	if (hasDebounced) await saveLayout()
}

export async function saveAssets(): Promise<void> {
	if (isStateLocked()) return saveAssetsLocked()
	return withStateLock(saveAssetsLocked)
}

async function saveAssetsLocked(): Promise<void> {
	if (isSavingAssets) {
		if (assetsSaveDebounceTimer) window.clearTimeout(assetsSaveDebounceTimer)
		assetsSaveDebounceTimer = window.setTimeout(() => saveAssets(), EDITOR_CONFIG.saveDebounceMs)
		return
	}

	isSavingAssets = true
	let hasDebounced = false
	try {
		const body = JSON.stringify({
			assetRegistry: state.assetRegistry,
		})

		const attemptSave = async (attempt: number): Promise<boolean> => {
			try {
				const res = await fetch(EDITOR_CONFIG.assetsSaveEndpoint, {
					method: 'POST',
					headers: { 'Content-Type': 'application/json', 'X-Blueprint-Save': '1' },
					body,
				})
				if (!res.ok) throw new Error(`HTTP ${res.status}`)
				return true
			} catch (e) {
				editorLog.error('saveAssets attempt ' + attempt, e)
				if (attempt < MAX_SAVE_RETRIES) {
					await new Promise(resolve => setTimeout(resolve, 1000 * (attempt + 1)))
					return attemptSave(attempt + 1)
				}
				return false
			}
		}

		const success = await attemptSave(1)
		if (!success) {
			editorLog.error('saveAssets', 'All retries failed')
			toast.error('Failed to save assets')
		}
	} finally {
		isSavingAssets = false
		if (assetsSaveDebounceTimer) {
			window.clearTimeout(assetsSaveDebounceTimer)
			assetsSaveDebounceTimer = null
			hasDebounced = true
		}
	}

	if (hasDebounced) await saveAssets()
}

const SYNC_KEY = EDITOR_CONFIG.syncKey

export function syncToGame(): boolean {
	try {
		const synced: Record<string, {
			defaultWalkable: boolean
			rooms: Array<{ id: string; x: number; y: number; w: number; h: number; label: string; sub: string; radius: number; roomType: string; walkable: boolean; entrances?: unknown[]; anchorPoints?: [number, number][]; tags?: string[] }>
			objects: Array<{ id: string; type: string; x: number; y: number; w: number; h: number; rotation: number; walkable: boolean; entranceRequired: boolean; walkableGrid?: boolean[][]; tileStates?: string[][]; roomId?: string; label?: string; fillColor?: string; tags?: string[] }>
			zones: Array<{ id: string; x: number; y: number; w: number; h: number; label: string; color: string; tags?: string[] }>
		}> = {}
		for (const floor of state.layout.floors) {
			const floorId = editorFloorLabelToFloorId(floor.label)
			if (!floorId) continue
			synced[floorId] = {
				defaultWalkable: floor.defaultWalkable ?? true,
				rooms: floor.rooms.map((r: RoomData) => ({
					id: r.id,
					x: r.x,
					y: r.y,
					w: r.w,
					h: r.h,
					label: r.label,
					sub: '',
					radius: r.radius ?? 0,
					roomType: r.roomType ?? 'room',
					walkable: r.walkable ?? true,
					...(r.entrances ? { entrances: r.entrances } : {}),
					...(r.anchorPoints ? { anchorPoints: r.anchorPoints } : {}),
					...(r.tags ? { tags: r.tags } : {}),
				})),
				zones: (floor.zones ?? []).map(z => ({ ...z })),
				objects: floor.objects.map((o: ObjectData) => ({
					id: o.id,
					type: o.type,
					x: o.x,
					y: o.y,
					w: o.w,
					h: o.h,
					rotation: o.rotation,
					fillColor: o.fillColor,
					walkable: o.walkable ?? !o.isWall,
					entranceRequired: o.entranceRequired ?? false,
					...(o.walkableGrid ? { walkableGrid: o.walkableGrid } : {}),
					...(o.tileStates ? { tileStates: o.tileStates } : {}),
					...(o.roomId ? { roomId: o.roomId } : {}),
					...(o.label ? { label: o.label } : {}),
					...((() => {
						const assetTags = assetMap().get(o.type)?.tags ?? []
						const tags = [...assetTags, ...(o.customProps?.tags ?? [])]
						return tags.length > 0 ? { tags: [...new Set(tags)] } : {}
					})()),
				})),
			}
		}
		localStorage.setItem(SYNC_KEY, JSON.stringify({
			version: 3,
			canvas: state.layout.canvas,
			npcConfig: state.layout.npcConfig,
			floors: synced,
			timestamp: Date.now(),
		}))
		window.dispatchEvent(new CustomEvent('blueprint:sync'))
		return true
	} catch (e) {
		if (e instanceof DOMException && e.name === 'QuotaExceededError') {
			toast.error('Sync failed - storage quota exceeded')
		} else {
			editorLog.error('syncToGame', e)
			toast.error('Sync failed - storage error')
		}
		return false
	}
}
