// Auto-generated by Blueprint Editor — 2026-07-05T10:23:24.729Z
import type { LayoutData } from './editor-types'

export const SAVED_LAYOUT: LayoutData = {
  "version": 1,
  "hiddenBuiltinIds": [
    "dining-table-round",
    "helipad",
    "filing-cabinet",
    "weapon-rack",
    "server-rack",
    "control-desk",
    "tv-stand",
    "minibar",
    "nightstand",
    "table-chairs",
    "luggage-rack",
    "storage-shelf",
    "prep-station",
    "kitchen-stove",
    "bar-stool"
  ],
  "roomCategories": [
    {
      "id": "public",
      "label": "Public / Guest",
      "color": "#e8e4dc",
      "builtin": true
    },
    {
      "id": "service",
      "label": "Guest Service",
      "color": "#d4e0f0",
      "builtin": true
    },
    {
      "id": "back",
      "label": "Back of House",
      "color": "#e0d4e8",
      "builtin": true
    },
    {
      "id": "security",
      "label": "Restricted / Security",
      "color": "#f0d4d4",
      "builtin": true
    },
    {
      "id": "utility",
      "label": "Utility",
      "color": "#d4e8d4",
      "builtin": true
    },
    {
      "id": "open",
      "label": "Open Area",
      "color": "#f7f7f5",
      "builtin": true
    }
  ],
  "assetCategories": [
    "Door",
    "Core",
    "Furniture",
    "Custom",
    "Merged",
    "Linked Sets",
    "Linked"
  ],
  "canvas": {
    "width": 1200,
    "height": 600,
    "tileSize": 25
  },
  "customAssets": [
    {
      "id": "door-standard",
      "name": "Door Standard",
      "category": "Door",
      "w": 1,
      "h": 1,
      "shape": "rect",
      "custom": true
    },
    {
      "id": "custom-mr6ishd7-1",
      "name": "Counter Side",
      "category": "Furniture",
      "w": 2,
      "h": 1,
      "shape": "rect",
      "custom": true
    },
    {
      "id": "wardrobe",
      "name": "Wardrobe",
      "category": "Furniture",
      "w": 1,
      "h": 2,
      "shape": "rect",
      "custom": true
    },
    {
      "id": "door-lobby",
      "name": "Door Lobby",
      "category": "Door",
      "w": 4,
      "h": 1,
      "shape": "rect",
      "custom": true
    },
    {
      "id": "elevator",
      "name": "Elevator",
      "category": "Core",
      "w": 3,
      "h": 4,
      "shape": "rect",
      "custom": true
    },
    {
      "id": "desk",
      "name": "Table",
      "category": "Furniture",
      "w": 1,
      "h": 2,
      "shape": "rect",
      "custom": true
    },
    {
      "id": "chair",
      "name": "Chair",
      "category": "Furniture",
      "w": 1,
      "h": 1,
      "shape": "rect",
      "custom": true,
      "defaultPadding": 5
    },
    {
      "id": "custom-mr7md5lk-1",
      "name": "Bar Chair",
      "category": "Furniture",
      "w": 1,
      "h": 1,
      "shape": "rect",
      "custom": true,
      "defaultPadding": 5
    },
    {
      "id": "linked-mr7n1jaa-1",
      "name": "Linked Set 5",
      "category": "Linked Sets",
      "w": 3,
      "h": 2,
      "shape": "rect",
      "custom": true,
      "linkedParts": [
        {
          "type": "desk",
          "dx": 25,
          "dy": 0,
          "w": 25,
          "h": 50,
          "rotation": 0
        },
        {
          "type": "chair",
          "dx": 50,
          "dy": 0,
          "w": 25,
          "h": 25,
          "rotation": 0
        },
        {
          "type": "chair",
          "dx": 50,
          "dy": 25,
          "w": 25,
          "h": 25,
          "rotation": 0
        },
        {
          "type": "chair",
          "dx": 0,
          "dy": 0,
          "w": 25,
          "h": 25,
          "rotation": 0
        },
        {
          "type": "chair",
          "dx": 0,
          "dy": 25,
          "w": 25,
          "h": 25,
          "rotation": 0
        }
      ]
    },
    {
      "id": "bar-counter",
      "name": "Bar Counter",
      "category": "Furniture",
      "w": 11,
      "h": 1,
      "shape": "rect",
      "custom": true
    }
  ],
  "floors": [
    {
      "id": "floor-F1",
      "name": "Lobby",
      "label": "F1",
      "rooms": [],
      "objects": [
        {
          "id": "o-mr6lgymj-1",
          "type": "door-lobby",
          "x": 400,
          "y": 0,
          "w": 100,
          "h": 25,
          "rotation": 0,
          "collapsed": false
        },
        {
          "id": "o-mr6lh345-2",
          "type": "door-lobby",
          "x": 700,
          "y": 0,
          "w": 100,
          "h": 25,
          "rotation": 0,
          "collapsed": false
        },
        {
          "id": "o-mr6xsin6-14",
          "type": "reception-counter",
          "x": 500,
          "y": 225,
          "w": 200,
          "h": 25,
          "rotation": 0,
          "collapsed": false
        },
        {
          "id": "o-mr6xtdha-16",
          "type": "custom-mr6ishd7-1",
          "x": 700,
          "y": 225,
          "w": 25,
          "h": 50,
          "rotation": 90,
          "collapsed": false
        },
        {
          "id": "o-mr6xtrw9-17",
          "type": "custom-mr6ishd7-1",
          "x": 475,
          "y": 225,
          "w": 25,
          "h": 50,
          "rotation": 90,
          "collapsed": false
        },
        {
          "id": "o-mr6xuryd-19",
          "type": "custom-mr6ishd7-1",
          "x": 1125,
          "y": 50,
          "w": 50,
          "h": 25,
          "rotation": 0,
          "collapsed": false
        },
        {
          "id": "o-mr7mqo76-1",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 50,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr12a-2",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 75,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr2g7-3",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 100,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr3lk-4",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 125,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr4tv-5",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 150,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr5xf-6",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 175,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr75r-7",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 200,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr8eq-8",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 225,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mr9v3-9",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 250,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mrbqm-10",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 275,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mrd39-11",
          "type": "custom-mr7md5lk-1",
          "x": 1075,
          "y": 300,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "rx": {
            "tl": 5,
            "tr": 5,
            "br": 5,
            "bl": 5
          },
          "padding": 5,
          "collapsed": false
        },
        {
          "id": "o-mr7mvvgr-1",
          "type": "desk",
          "x": 975,
          "y": 50,
          "w": 25,
          "h": 50,
          "rotation": 0,
          "linkedIds": [
            "o-mr7mwgou-4",
            "o-mr7mwhzx-5",
            "o-mr7mwl8a-6",
            "o-mr7mwmcw-7"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7mwgou-4",
          "type": "chair",
          "x": 1000,
          "y": 50,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "padding": 5,
          "linkedIds": [
            "o-mr7mvvgr-1",
            "o-mr7mwhzx-5",
            "o-mr7mwl8a-6",
            "o-mr7mwmcw-7"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7mwhzx-5",
          "type": "chair",
          "x": 1000,
          "y": 75,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "padding": 5,
          "linkedIds": [
            "o-mr7mvvgr-1",
            "o-mr7mwgou-4",
            "o-mr7mwl8a-6",
            "o-mr7mwmcw-7"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7mwl8a-6",
          "type": "chair",
          "x": 950,
          "y": 50,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "padding": 5,
          "linkedIds": [
            "o-mr7mvvgr-1",
            "o-mr7mwgou-4",
            "o-mr7mwhzx-5",
            "o-mr7mwmcw-7"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7mwmcw-7",
          "type": "chair",
          "x": 950,
          "y": 75,
          "w": 25,
          "h": 25,
          "rotation": 0,
          "padding": 5,
          "linkedIds": [
            "o-mr7mvvgr-1",
            "o-mr7mwgou-4",
            "o-mr7mwhzx-5",
            "o-mr7mwl8a-6"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n5rnk-1",
          "type": "desk",
          "rotation": 0,
          "x": 975,
          "y": 125,
          "w": 25,
          "h": 50,
          "linkedIds": [
            "o-mr7n5rnk-2",
            "o-mr7n5rnk-3",
            "o-mr7n5rnk-4",
            "o-mr7n5rnk-5"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n5rnk-2",
          "type": "chair",
          "rotation": 0,
          "x": 1000,
          "y": 125,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n5rnk-1",
            "o-mr7n5rnk-3",
            "o-mr7n5rnk-4",
            "o-mr7n5rnk-5"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n5rnk-3",
          "type": "chair",
          "rotation": 0,
          "x": 1000,
          "y": 150,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n5rnk-1",
            "o-mr7n5rnk-2",
            "o-mr7n5rnk-4",
            "o-mr7n5rnk-5"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n5rnk-4",
          "type": "chair",
          "rotation": 0,
          "x": 950,
          "y": 125,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n5rnk-1",
            "o-mr7n5rnk-2",
            "o-mr7n5rnk-3",
            "o-mr7n5rnk-5"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n5rnk-5",
          "type": "chair",
          "rotation": 0,
          "x": 950,
          "y": 150,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n5rnk-1",
            "o-mr7n5rnk-2",
            "o-mr7n5rnk-3",
            "o-mr7n5rnk-4"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n61xu-6",
          "type": "desk",
          "rotation": 0,
          "x": 975,
          "y": 200,
          "w": 25,
          "h": 50,
          "linkedIds": [
            "o-mr7n61xu-7",
            "o-mr7n61xu-8",
            "o-mr7n61xu-9",
            "o-mr7n61xu-10"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n61xu-7",
          "type": "chair",
          "rotation": 0,
          "x": 1000,
          "y": 200,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n61xu-6",
            "o-mr7n61xu-8",
            "o-mr7n61xu-9",
            "o-mr7n61xu-10"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n61xu-8",
          "type": "chair",
          "rotation": 0,
          "x": 1000,
          "y": 225,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n61xu-6",
            "o-mr7n61xu-7",
            "o-mr7n61xu-9",
            "o-mr7n61xu-10"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n61xu-9",
          "type": "chair",
          "rotation": 0,
          "x": 950,
          "y": 200,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n61xu-6",
            "o-mr7n61xu-7",
            "o-mr7n61xu-8",
            "o-mr7n61xu-10"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n61xu-10",
          "type": "chair",
          "rotation": 0,
          "x": 950,
          "y": 225,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n61xu-6",
            "o-mr7n61xu-7",
            "o-mr7n61xu-8",
            "o-mr7n61xu-9"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n66ux-11",
          "type": "desk",
          "rotation": 0,
          "x": 975,
          "y": 275,
          "w": 25,
          "h": 50,
          "linkedIds": [
            "o-mr7n66ux-12",
            "o-mr7n66ux-13",
            "o-mr7n66ux-14",
            "o-mr7n66ux-15"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n66ux-12",
          "type": "chair",
          "rotation": 0,
          "x": 1000,
          "y": 275,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n66ux-11",
            "o-mr7n66ux-13",
            "o-mr7n66ux-14",
            "o-mr7n66ux-15"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n66ux-13",
          "type": "chair",
          "rotation": 0,
          "x": 1000,
          "y": 300,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n66ux-11",
            "o-mr7n66ux-12",
            "o-mr7n66ux-14",
            "o-mr7n66ux-15"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n66ux-14",
          "type": "chair",
          "rotation": 0,
          "x": 950,
          "y": 275,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n66ux-11",
            "o-mr7n66ux-12",
            "o-mr7n66ux-13",
            "o-mr7n66ux-15"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n66ux-15",
          "type": "chair",
          "rotation": 0,
          "x": 950,
          "y": 300,
          "w": 25,
          "h": 25,
          "padding": 5,
          "linkedIds": [
            "o-mr7n66ux-11",
            "o-mr7n66ux-12",
            "o-mr7n66ux-13",
            "o-mr7n66ux-14"
          ],
          "collapsed": false
        },
        {
          "id": "o-mr7n75fq-16",
          "type": "bar-counter",
          "rotation": 270,
          "x": 1100,
          "y": 50,
          "w": 25,
          "h": 275,
          "collapsed": false
        }
      ],
      "zones": []
    }
  ]
}
