import type { RoomData } from '../types'
import { state, editorLog, toast, editorFloorLabelToFloorId, EDITOR_CONFIG } from './state'
import { validateLayoutData } from '../types'

let saveDebounceTimer: number | null = null
let isSaving = false
const MAX_SAVE_RETRIES = 3
const BACKUP_KEY = 'blueprint-layout-backup'
const BACKUP_INTERVAL = 60000 // 1 minute

let backupTimer: number | null = null

export function startBackupTimer() {
  if (backupTimer) window.clearInterval(backupTimer)
  backupTimer = window.setInterval(() => {
    try {
      const backup = JSON.stringify(state.layout)
      localStorage.setItem(BACKUP_KEY, backup)
    } catch (e) {
      editorLog.error('saveBackup', e)
    }
  }, BACKUP_INTERVAL)
}

export function stopBackupTimer() {
  if (backupTimer) {
    window.clearInterval(backupTimer)
    backupTimer = null
  }
}

export function loadBackup(): boolean {
  try {
    const backup = localStorage.getItem(BACKUP_KEY)
    if (!backup) return false
    const parsed = JSON.parse(backup)
    const validated = validateLayoutData(parsed)
    if (validated) {
      state.layout = validated
      editorLog.info('Loaded from backup')
      return true
    }
  } catch (e) {
    editorLog.error('loadBackup', e)
  }
  return false
}

export async function saveLayout() {
  if (isSaving) {
    if (saveDebounceTimer) window.clearTimeout(saveDebounceTimer)
    saveDebounceTimer = window.setTimeout(() => saveLayout(), EDITOR_CONFIG.saveDebounceMs)
    return
  }

  isSaving = true
  const data = state.layout
  const ts = `// Auto-generated by Blueprint Editor - ${new Date().toISOString()}
import type { LayoutData } from '../types'

const SAVED_LAYOUT: LayoutData = ${JSON.stringify(data, null, 2)}
`

  const attemptSave = async (attempt: number): Promise<boolean> => {
    try {
      const res = await fetch(EDITOR_CONFIG.saveEndpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'text/plain' },
        body: ts,
      })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      return true
    } catch (e) {
      editorLog.error('saveLayout attempt ' + attempt, e)
      if (attempt < MAX_SAVE_RETRIES) {
        await new Promise(resolve => setTimeout(resolve, 1000 * (attempt + 1)))
        return attemptSave(attempt + 1)
      }
      return false
    }
  }

  const success = await attemptSave(1)
  if (!success) {
    editorLog.error('saveLayout', 'All retries failed')
    toast.error('Failed to save - falling back to download')
    const blob = new Blob([ts], { type: 'text/typescript' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'assets-store-layout.ts'
    a.click()
    URL.revokeObjectURL(url)
  }

  isSaving = false
  if (saveDebounceTimer) {
    window.clearTimeout(saveDebounceTimer)
    saveDebounceTimer = null
    saveLayout()
  }
}

const SYNC_KEY = EDITOR_CONFIG.syncKey

export function syncToGame(): boolean {
  try {
    const synced: Record<string, Array<{ id: string; x: number; y: number; w: number; h: number; label: string; sub: string; radius: number }>> = {}
    for (const floor of state.layout.floors) {
      const floorId = editorFloorLabelToFloorId(floor.label)
      if (!floorId) continue
      synced[floorId] = floor.rooms.map((r: RoomData) => ({
        id: r.id,
        x: r.x,
        y: r.y,
        w: r.w,
        h: r.h,
        label: r.label,
        sub: '',
        radius: r.radius ?? 0,
      }))
    }
    localStorage.setItem(SYNC_KEY, JSON.stringify({ version: 1, floors: synced, timestamp: Date.now() }))
    return true
  } catch (e) {
    if (e instanceof DOMException && e.name === 'QuotaExceededError') {
      toast.error('Sync failed - storage quota exceeded')
    } else {
      editorLog.error('syncToGame', e)
      toast.error('Sync failed - storage error')
    }
    return false
  }
}
