/**
 * selftest.ts - the failure library run as a test.
 *
 * A validator that cannot catch a known-bad plan is not a validator; one that fires on a
 * known-good plan is noise. This drives every fixture through the real pipeline - migrate, the
 * host engine, the world model, the checks - and asserts:
 *   bad  fixtures produce the findings they are documented to produce
 *   good fixtures produce none of the findings they are documented to be free of
 * It also renders each fixture and regenerates architecture-skill/failure-library.md from the
 * measured results, so the documentation cannot drift away from the executable examples.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { TAKING_RATES_CENTS } from '../../src/blueprint-editor/domain/economy/takings'
import { buildLobby } from './build-lobby'
import { CAPABILITY_MANIFEST, CLOSURE_RIGHTS, evaluate } from './evaluate'
import { diffDistance, distinctAlternatives, economyFromReport, formatComparison, measureOption, paretoSet, rankOptions, RANKED_KEYS, WEIGHT_PROFILES, type OptionEconomy } from './compare'
import { FIXTURE_FLOOR_ID, fixtureFloors, fixtureFloorId, FIXTURES, fixtureToDataFile, type Fixture } from './fixtures'
import { buildingKpis, entryCell, floorKpis, regressions } from './metrics'
import { renderAscii, renderContactSheet, renderPng, renderSvg } from './render'
import { metricRows, probeMinimality, revise, type Patch } from './revise'
import { measureTakings } from './takings'
import { loadWorld } from './world'
import type { EvaluationReport } from './types'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '../..')
const WORK = path.join(HERE, 'out', 'fixtures')
const LIBRARY = path.join(ROOT, 'architecture-skill', 'failure-library.md')

/** The fixture whose documented repair is a pure retag, so the repair stage has something to prove. */
const REPAIR_FIXTURE = 'bad-untagged-room'
/** A fixture carrying a critical gate failure, so the compare stage has something to reject. */
const BLOCKED_FIXTURE = 'bad-single-file-corridor'

function findingIds(report: EvaluationReport): Set<string> {
	return new Set([...report.floors.flatMap(floor => floor.findings.map(finding => finding.id)), ...report.building.findings.map(finding => finding.id)])
}

function sofaRetagPatch(): Patch {
	return {
		intent: 'place the discriminating fixture in every enclosed region so none of them resolves to hallway',
		targets: ['INT-04'],
		rung: 'retag',
		ops: [
			{ op: 'addObject', floor: FIXTURE_FLOOR_ID, id: 'sofa-left', type: 'fx-sofa', x: 6, y: 6 },
			{ op: 'addObject', floor: FIXTURE_FLOOR_ID, id: 'sofa-right', type: 'fx-sofa', x: 14, y: 6 },
			{ op: 'addObject', floor: FIXTURE_FLOOR_ID, id: 'sofa-bottom', type: 'fx-sofa', x: 11, y: 11 },
		],
	}
}

interface FixtureRun {
	fixture: Fixture
	report: EvaluationReport
	ids: Set<string>
	missing: string[]
	unexpected: string[]
	planPath: string
	/** One picture per storey - a section failure is invisible in a single-floor drawing. */
	renders: { floorId: string; label: string; pngPath: string }[]
}

function runFixtures(): FixtureRun[] {
	fs.mkdirSync(WORK, { recursive: true })
	return FIXTURES.map(fixture => {
		const planPath = path.join(WORK, `${fixture.id}.json`)
		fs.writeFileSync(planPath, `${JSON.stringify(fixtureToDataFile(fixture), null, 1)}\n`)
		const bundle = loadWorld(planPath)
		const report = evaluate(bundle)
		const ids = findingIds(report)

		// A bad fixture must produce its documented findings. A good fixture must produce none of
		// the findings it claims to be free of - that list is the control, and it is the one that
		// catches a validator drifting into noise.
		const missing = fixture.polarity === 'bad' ? fixture.expect.filter(id => !ids.has(id)) : []
		const unexpected = fixture.polarity === 'good' ? fixture.expect.filter(id => ids.has(id)) : []

		const findingsByFloor = new Map(report.floors.map(floor => [floor.floorId, floor.findings]))
		const building = report.building.findings
		const renders = bundle.world.floors.map(floor => {
			const findings = [...(findingsByFloor.get(floor.id) ?? []), ...building]
			const pngPath = path.join(WORK, `${fixture.id}.${floor.id}.png`)
			fs.writeFileSync(pngPath, renderPng(floor, { scale: 10, findings }).png)
			fs.writeFileSync(path.join(WORK, `${fixture.id}.${floor.id}.ascii.txt`), `${renderAscii(floor, bundle.world, { findings })}\n`)
			return { floorId: floor.id, label: floor.label, pngPath }
		})

		return { fixture, report, ids, missing, unexpected, planPath, renders }
	})
}

function formatLibrary(runs: readonly FixtureRun[]): string {
	const lines: string[] = [
		'# Failure Library',
		'',
		'Generated by `npm run arch:selftest` from the executable fixtures in `scripts/arch/fixtures.ts`.',
		'Do not edit this file by hand - edit the fixture and re-run, or the examples and the prose will diverge.',
		'',
		'Research that only collects good architecture teaches an agent what to aim at and nothing about what to',
		'reject. Every entry below is a deliberately broken plan, its picture, the reason it is bad, the finding',
		'ids the harness must fire on it, and the cheapest repair. The plans are ASCII, so the defect is visible',
		'before it is measured - which is the order an architect works in.',
		'',
		'Legend: `#` blocked / wall   `.` walkable floor   `+` door   1 tile = 0.5 m',
		'',
	]

	for (const run of runs) {
		const { fixture, report, ids, renders } = run
		lines.push(`## ${fixture.name}`)
		lines.push('')
		lines.push(`- fixture id: \`${fixture.id}\``)
		lines.push(`- polarity: **${fixture.polarity}**`)
		lines.push(`- rules: ${fixture.rules.map(rule => `\`${rule}\``).join(', ')}`)
		lines.push(`- expected finding ids: ${fixture.expect.map(id => `\`${id}\``).join(', ')}`)
		lines.push(`- measured: ${[...ids].sort().join(', ') || 'none'}`)
		lines.push(`- verdict: ${report.verdict.toUpperCase()}  (${report.counts.critical} critical / ${report.counts.major} major / ${report.counts.moderate} moderate / ${report.counts.minor} minor)`)
		lines.push(`- storeys: ${renders.length} (${renders.map(render => `\`${render.floorId}\``).join(' ')})`)
		lines.push(`- pictures: ${renders.map(render => `\`scripts/arch/out/fixtures/${path.basename(render.pngPath)}\``).join(', ')}`)
		lines.push('')
		if (fixture.whyBad) {
			lines.push('**Why this is bad.** ' + fixture.whyBad)
			lines.push('')
		}
		if (fixture.correction) {
			lines.push('**Cheapest repair.** ' + fixture.correction)
			lines.push('')
		}
		const storeys = fixtureFloors(fixture)
		for (const storey of storeys) {
			if (storeys.length > 1) lines.push(`_${storey.label} — \`${storey.id}\`_`)
			lines.push('```')
			lines.push(...storey.plan)
			lines.push('```')
			lines.push('')
		}
		if (fixture.polarity === 'bad') {
			const findings = [...report.floors.flatMap(f => f.findings), ...report.building.findings]
				.filter(finding => fixture.expect.includes(finding.id))
			if (findings.length) {
				lines.push('**What the harness measured:**')
				lines.push('')
				for (const finding of findings) {
					lines.push(`- \`${finding.id}\` ${finding.check} [${finding.severity}] - ${finding.metric} = ${finding.actual}; required ${finding.required}`)
					lines.push(`  - rule: ${finding.rule}`)
					lines.push(`  - repair: ${finding.correction}`)
				}
				lines.push('')
			}
		}
		if (run.missing.length) lines.push(`> **LIBRARY DEFECT** - expected but not fired: ${run.missing.join(', ')}`)
		if (run.unexpected.length) lines.push(`> **CONTROL DEFECT** - fired on the good fixture: ${run.unexpected.join(', ')}`)
		lines.push('---')
		lines.push('')
	}

	lines.push('## How to add an example')
	lines.push('')
	lines.push('1. Draw the plan in `scripts/arch/fixtures.ts` as ASCII - the defect must be visible in the drawing.')
	lines.push('2. Write `whyBad` (the mechanism, not the adjective) and `correction` (the cheapest rung of the blast-radius ladder).')
	lines.push('3. List the finding ids it must fire in `expect`, and the rule ids it instantiates in `rules`.')
	lines.push('4. Run `npm run arch:selftest`. It re-renders, re-measures and rewrites this file.')
	lines.push('')
	lines.push('A fixture whose expected finding does not fire is a bug in the validator, not in the fixture: fix the')
	lines.push('validator. A finding that fires on `good-double-loaded` is noise: raise its threshold or drop it.')
	return lines.join('\n')
}

/**
 * The repair stage is a contract, not a narrative: a patch earns credit only for what it claimed,
 * and every cascade it reports must be reproducible from the two reports. If this drifts, `revise`
 * has started believing the generator again - the one thing this harness exists to prevent.
 */
function runRepairChecks(runs: readonly FixtureRun[]): string[] {
	const target = runs.find(run => run.fixture.id === REPAIR_FIXTURE)
	const control = runs.find(run => run.fixture.polarity === 'good')
	if (!target || !control) return [`repair fixtures missing: ${REPAIR_FIXTURE} and/or the good control`]
	const failures: string[] = []

	const empty = revise(control.planPath, { intent: 'no-op', targets: ['GATE-01', 'CIR-01'], rung: 'retag', ops: [] }, path.join(WORK, 'repair-noop.json'))
	if (empty.cleared.length) failures.push(`a no-op patch was credited with clearing ${empty.cleared.join(', ')}`)
	if (empty.introduced.length) failures.push(`a no-op patch introduced ${empty.introduced.join(', ')}`)

	const patch = sofaRetagPatch()
	const result = revise(target.planPath, patch, path.join(WORK, 'repair-retagged.json'))
	if (!result.cleared.includes('INT-04')) failures.push(`the retag repair did not clear INT-04 (cleared: ${result.cleared.join(', ') || 'none'})`)

	const before = findingIds(result.before)
	const after = findingIds(result.after)
	const claimed = new Set(patch.targets)
	for (const id of result.cleared) {
		if (!claimed.has(id) || !before.has(id) || after.has(id)) failures.push(`cleared "${id}" is not a claimed finding present before and absent after`)
	}
	for (const id of result.stillOpen) {
		if (!claimed.has(id) || !after.has(id)) failures.push(`still open "${id}" is not a claimed finding that is still firing`)
	}
	for (const id of result.introduced) {
		if (claimed.has(id) || before.has(id) || !after.has(id)) failures.push(`introduced "${id}" is not an unclaimed finding that newly appeared`)
	}

	// The rung the patch declares is a claim too. Adding a fixture is a retag; deleting the core is not,
	// whatever the label says, and an understated rung hides the blast radius that R6 exists to limit.
	if (result.rung.effective !== 'retag' || result.rung.understated) failures.push(`the sofa retag measured as "${result.rung.effective}" - placing a fixture moves no geometry`)
	const lift = loadWorld(target.planPath).world.floors[0].portals[0]?.objectId
	if (!lift) failures.push(`${REPAIR_FIXTURE} has no portal to test the rung ladder against`)
	else {
		const lying = revise(target.planPath, {
			intent: 'delete the lift', targets: [], rung: 'retag',
			ops: [{ op: 'removeObject', floor: FIXTURE_FLOOR_ID, id: lift }],
		}, path.join(WORK, 'rung-understated.json'))
		if (lying.rung.effective !== 'core') failures.push(`removing portal "${lift}" declared "retag" measured as "${lying.rung.effective}"`)
		if (!lying.rung.understated) failures.push('a retag label on a core operation was not reported as understated')
		if (!lying.rung.reasons.length) failures.push('the rung escalation carried no reason, so it cannot be argued with')

		const wide = revise(target.planPath, {
			intent: 'open a strip of floor', targets: [], rung: 'door',
			ops: [{ op: 'fillRect', floor: FIXTURE_FLOOR_ID, x0: 6, y0: 4, x1: 14, y1: 4, state: 'walkable' }],
		}, path.join(WORK, 'rung-wall.json'))
		if (wide.rung.effective !== 'wall') failures.push(`a nine-cell tile write measured as "${wide.rung.effective}", expected "wall"`)
	}

	// Rung minimality. Which operations are load-bearing is measured, not assumed: the three-sofa retag
	// above turns out to contain one redundant placement, because tagging two of the regions is enough
	// to clear INT-04 - the third is blast radius the repair did not need.
	const inert = { op: 'setTile', floor: FIXTURE_FLOOR_ID, x: 0, y: 0, state: 'walkable' } as const
	const bloated: Patch = { ...patch, ops: [...patch.ops, inert] }
	const padded = probeMinimality(target.planPath, bloated, path.join(WORK, 'probe-bloated.json'))
	const lean = probeMinimality(target.planPath, patch, path.join(WORK, 'probe-lean.json'))

	if (padded.alreadyMinimal) failures.push('the minimality probe called a patch containing a demonstrably inert tile write already minimal')
	if (!padded.spare.some(op => op.op === 'setTile' && op.x === 0 && op.y === 0)) failures.push('the probe did not identify the inert street-cell write as spare')
	if (lean.alreadyMinimal || lean.minimal.length >= patch.ops.length) failures.push(`the probe found no redundancy in a ${patch.ops.length}-op retag that measurably has some`)
	if (lean.capped) failures.push('the probe hit its trial cap on a three-operation patch')

	// The probe's own claim, checked independently: applying only what it calls necessary must still
	// clear everything the full patch cleared. A savings that does not survive re-measurement is noise.
	for (const [label, probe] of [['bloated', padded], ['lean', lean]] as const) {
		if (!probe.cleared.includes('INT-04')) failures.push(`the ${label} probe lost the INT-04 clearance, so the bar it holds is unstable`)
		const check = revise(target.planPath, { ...patch, ops: probe.minimal }, path.join(WORK, `probe-verify-${label}.json`))
		if (!check.cleared.includes('INT-04')) failures.push(`the ${label} probe's minimal subset (${probe.minimal.length} ops) does not actually clear INT-04`)
		if (probe.minimal.some(op => op.op === 'setTile')) failures.push(`the ${label} probe kept the inert tile write in its minimal subset`)
	}

	// The hole this classifier exists to close. Under a size ranking, tagging every region but one read
	// as a clean repair - the last mistyped room was by definition the largest hall, so it became the
	// circulation. It must stay open now.
	const partial = revise(target.planPath, {
		intent: 'tag two of the three enclosed regions and leave one as hallway',
		targets: ['INT-04'], rung: 'retag',
		ops: [
			{ op: 'addObject', floor: FIXTURE_FLOOR_ID, id: 'partial-right', type: 'fx-sofa', x: 14, y: 6 },
			{ op: 'addObject', floor: FIXTURE_FLOOR_ID, id: 'partial-bottom', type: 'fx-sofa', x: 11, y: 11 },
		],
	}, path.join(WORK, 'partial-retag.json'))
	if (partial.cleared.includes('INT-04') || !findingIds(partial.after).has('INT-04')) failures.push('a repair leaving one mistyped room standing was accepted as clearing INT-04')

	// The metric diff is the numeric account of a repair. It must add up, and it must show the
	// mechanism INT-04 describes: programme recovered, and the circulation share that the lost room
	// was inflating comes down.
	const rows = metricRows(target.planPath, path.join(WORK, 'repair-retagged.json'))
	if (!rows.length) failures.push('metricRows produced no rows for a repair that changed the plan')
	for (const row of rows) {
		if (!row.presenceOnly && row.delta !== Number((row.after - row.before).toFixed(4))) failures.push(`${row.metric} delta ${row.delta} disagrees with after-minus-before`)
	}
	for (const [metric, want] of [['roomTiles', 1], ['untaggedRoomCount', -1], ['circulationShare', -1]] as const) {
		const row = rows.find(candidate => candidate.metric === metric)
		if (!row) failures.push(`the metric diff is missing ${metric}`)
		else if (Math.sign(row.delta) !== want) failures.push(`${metric} moved ${row.delta} after the retag; expected sign ${want}`)
	}
	// A payload diffed against itself must move nothing - the easiest way for a diff to lie is to
	// recompute something non-deterministically and call the noise a change.
	const still = metricRows(control.planPath, control.planPath)
	const drifted = still.filter(row => row.delta !== 0)
	if (drifted.length) failures.push(`diffing a payload against itself moved ${drifted.length} metric(s): ${drifted.map(row => row.metric).join(', ')}`)
	return failures
}

/**
 * A block's own money reading, so the stage ranks on the same columns `--economy` publishes. A third of
 * a day is enough: the profit KPI is a projection of the measured rate, and the claim here is that the
 * column exists and is finite for every option, not that the day closed. This became possible when
 * fixture payloads started passing the strict ingress (loop 68) - `measureTakings` reads through it.
 */
function economyOf(planPath: string): OptionEconomy {
	return economyFromReport(measureTakings(planPath, { ticks: Math.floor(ECONOMY_TICKS / 3), agents: 12 }))
}

/** An option with a critical finding is a broken plan, so it may never appear in a ranking at all. */
function runCompareChecks(runs: readonly FixtureRun[]): string[] {
	const control = runs.find(run => run.fixture.polarity === 'good')
	const blocked = runs.find(run => run.fixture.id === BLOCKED_FIXTURE)
	if (!control || !blocked) return [`compare fixtures missing: ${BLOCKED_FIXTURE} and/or the good control`]
	const failures: string[] = []

	const options = [measureOption('good', control.planPath, economyOf(control.planPath)), measureOption('broken', blocked.planPath, economyOf(blocked.planPath))]
	const broken = options[1]
	if (options[0].disqualified) failures.push('the control option was disqualified by a critical finding')
	if (!broken.disqualified) failures.push(`"${BLOCKED_FIXTURE}" carries a critical finding but was not disqualified`)
	if (!broken.blockers.length) failures.push('a disqualified option reported no blocking finding id')

	for (const profile of Object.keys(WEIGHT_PROFILES)) {
		if (rankOptions(options, profile).order.some(entry => entry.name === broken.name)) failures.push(`rankOptions("${profile}") ranked a disqualified option`)
	}
	if (paretoSet(options).includes(broken.name)) failures.push('the Pareto set contained a disqualified option')

	// Every option is scored on the identical metric list; a missing key silently reads as zero and
	// quietly reweights the comparison in whoever happens to be missing it's favour.
	for (const option of options) {
		const keys = new Set(option.kpis.map(kpi => kpi.key))
		const absent = RANKED_KEYS.filter(key => !keys.has(key))
		if (absent.length) failures.push(`${option.name} was not measured on ${absent.join(', ')}`)
	}

	// One source for the limits. The comparison and the evaluation report must state the same
	// boundaries, or a reader gets two different answers about what this harness cannot decide.
	const report = formatComparison(options)
	for (const limit of CAPABILITY_MANIFEST.cannotRun) {
		if (!report.includes(limit)) failures.push(`the comparison omits a limit the evaluation report states: "${limit}"`)
	}
	for (const right of CLOSURE_RIGHTS) {
		if (!report.includes(right)) failures.push(`the comparison omits a closure right the evaluation report states: "${right}"`)
	}
	if (!CAPABILITY_MANIFEST.cannotRun.length || !CLOSURE_RIGHTS.length) failures.push('the shared limits or closure-rights lists are empty, so the drift guard above proves nothing')

	// The documentation is the same contract, not a summary of it. This section had drifted to naming
	// five of the eight limits, which is how a document ends up under-declaring what the tool cannot do.
	const readme = fs.readFileSync(path.join(ROOT, 'scripts', 'arch', 'README.md'), 'utf8')
	if (!readme.includes('## What the harness cannot decide')) failures.push('scripts/arch/README.md lost its limits section')
	for (const limit of CAPABILITY_MANIFEST.cannotRun) {
		if (!readme.includes(limit)) failures.push(`scripts/arch/README.md no longer states the limit "${limit}" - it has drifted from CAPABILITY_MANIFEST`)
	}

	// A multi-storey option must not have its per-floor gates added up. Three reconciled floors used to
	// print "3" for a 0/1 metric, which reads as a healthy building and is an arithmetic artifact.
	const stacked = runs.find(run => run.fixture.id === DRIFT_FIXTURE)
	if (stacked) {
		const stackedOption = measureOption('stacked', stacked.planPath)
		const table = formatComparison([stackedOption])
		const boolRow = /^\s*tile-class reconciliation \(bool\)\s+([\d.]+)/m.exec(table)
		if (!boolRow) failures.push('the comparison table no longer publishes the tile-class reconciliation gate')
		else if (Number(boolRow[1]) > 1) failures.push(`a boolean gate printed ${boolRow[1]} for a three-storey option; per-floor values are being summed again`)
		if (!table.includes('Per-storey folding')) failures.push('the comparison table does not disclose how per-storey values were folded')
		// Prove the worst-floor branch actually fires, instead of trusting that the number looks right.
		const candidates = stackedOption.kpis.filter(kpi => kpi.gate && kpi.direction === 'down')
		const distinguishing = candidates.find(kpi => {
			const values = candidates.filter(other => other.key === kpi.key).map(other => other.value)
			return values.length > 1 && Math.max(...values) !== values.reduce((sum, value) => sum + value, 0) / values.length
		})
		if (!distinguishing) failures.push('no gate metric differs between worst-floor and mean on a three-storey option, so the fold branch is untested')
		else {
			const worst = Math.max(...candidates.filter(kpi => kpi.key === distinguishing.key).map(kpi => kpi.value))
			const escaped = distinguishing.label.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
			const row = new RegExp(`^[* ]${escaped} \\([^)]*\\)\\s+([\\d.]+)`, 'm').exec(table)
			if (!row) failures.push(`the comparison table has no row for ${distinguishing.label}`)
			else if (Math.abs(Number(row[1]) - Number(worst.toFixed(2))) > 0.011) failures.push(`${distinguishing.label} printed ${row[1]} but the worst floor is ${worst} - gates are not folding by worst case`)
		}
	}

	// Variants are not alternatives. Two copies of one plan must collapse and the comparison must
	// refuse, because a ranking of identical inputs manufactures a trade-off nobody designed.
	const twin = measureOption('twin', control.planPath)
	const distance = diffDistance(options[0], twin)
	if (distance !== 0) failures.push(`two loads of the same plan differ on ${distance} diff components - the diff vector is not deterministic`)
	if (distinctAlternatives([options[0], twin]).length !== 1) failures.push('two copies of one plan survived as distinct alternatives')
	const REFUSAL = /^-\s+(efficiency|experience|operations|safety)\s+->/m
	if (REFUSAL.test(formatComparison([options[0], twin]))) failures.push('compare printed a ranking for a set with no distinct alternatives')

	// And the guard must not swallow real alternatives: two unblocked plans that genuinely differ
	// still have to rank, or "cannot rank" has become the new way to say nothing.
	const second = runs.find(run => run.fixture.id === REPAIR_FIXTURE)
	if (second) {
		const pair = [options[0], measureOption('variant-check', second.planPath)]
		if (distinctAlternatives(pair).length < 2) failures.push(`${REPAIR_FIXTURE} and the control collapsed into one alternative - the diff vector cannot tell real designs apart`)
		if (!REFUSAL.test(formatComparison(pair))) failures.push('compare refused to rank two distinct, unblocked alternatives')
	}
	return failures
}

/** The section examples put the deviating car on the third storey; the two below it stack. */
const DRIFT_FIXTURE = 'bad-drifting-lift'
const NO_LIFT_FIXTURE = 'bad-floor-no-lift'
const TOP_FLOOR = fixtureFloorId(2)

/**
 * Attribution, not just detection. A section finding has to name the storey that moved and leave the
 * ones that already stack alone, or the repair it recommends breaks a core that was working.
 */
function runVerticalChecks(runs: readonly FixtureRun[]): string[] {
	const drift = runs.find(run => run.fixture.id === DRIFT_FIXTURE)
	const stranded = runs.find(run => run.fixture.id === NO_LIFT_FIXTURE)
	if (!drift || !stranded) return [`section fixtures missing: ${DRIFT_FIXTURE} and/or ${NO_LIFT_FIXTURE}`]
	const failures: string[] = []

	const drifted = loadWorld(drift.planPath).world
	if (drifted.floors.length !== 3) failures.push(`${DRIFT_FIXTURE} derived ${drifted.floors.length} storeys, expected 3`)
	if (!drifted.vertical.stackedPortalKeys.length) failures.push(`${DRIFT_FIXTURE}: the two aligned storeys produced no consensus stack, so drift cannot be attributed`)
	if (drifted.vertical.stackDrift.length !== 1) {
		failures.push(`${DRIFT_FIXTURE}: ${drifted.vertical.stackDrift.length} storeys blamed for drift, expected 1 (${drifted.vertical.stackDrift.map(entry => entry.floorId).join(', ') || 'none'})`)
	}
	const blamed = drifted.vertical.stackDrift[0]
	if (blamed && blamed.floorId !== TOP_FLOOR) failures.push(`${DRIFT_FIXTURE} blamed "${blamed.floorId}", but the car that moved is on "${TOP_FLOOR}"`)
	if (blamed && (!blamed.extra.length || !blamed.missing.length)) failures.push(`${DRIFT_FIXTURE}: the blamed storey names no off-stack or missing cells, so the finding points at nothing`)

	const cutOff = loadWorld(stranded.planPath).world
	if (!cutOff.vertical.floorsWithoutPortals.includes(TOP_FLOOR)) failures.push(`${NO_LIFT_FIXTURE}: "${TOP_FLOOR}" has no portal but was not listed as vertically cut off`)
	if (cutOff.vertical.stackDrift.length) failures.push(`${NO_LIFT_FIXTURE} reported drift between the two storeys that do stack (${cutOff.vertical.stackDrift.map(entry => entry.floorId).join(', ')})`)
	return failures
}

const PNG_SIGNATURE = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]

function be32(bytes: Uint8Array, at: number): number {
	return (bytes[at] << 24) | (bytes[at + 1] << 16) | (bytes[at + 2] << 8) | bytes[at + 3]
}

/** Walk the chunk stream the way a decoder would, so a file the browser rejects fails here first. */
function pngChunkTypes(bytes: Uint8Array): string[] {
	for (let i = 0; i < PNG_SIGNATURE.length; i++) if (bytes[i] !== PNG_SIGNATURE[i]) return []
	const types: string[] = []
	let offset = 8
	while (offset + 8 <= bytes.length) {
		const length = be32(bytes, offset)
		const from = offset + 4
		types.push(String.fromCharCode(bytes[from], bytes[from + 1], bytes[from + 2], bytes[from + 3]))
		offset += 12 + length
	}
	return types
}

/**
 * The protocol's first rule is "look at the picture", so a renderer that silently emits a blank or
 * truncated file degrades the whole loop without any signal. This checks the bytes a decoder reads,
 * the composition of a contact sheet, and that what was derived is what got drawn.
 */
function runRenderChecks(runs: readonly FixtureRun[]): string[] {
	const control = runs.find(run => run.fixture.polarity === 'good')
	const stack = runs.find(run => run.fixture.id === DRIFT_FIXTURE)
	if (!control || !stack) return ['render fixtures missing: the good control and/or the stacked core']
	const failures: string[] = []

	const bundle = loadWorld(control.planPath)
	const floor = bundle.world.floors[0]
	const drawing = renderPng(floor, { scale: 6 })
	const types = pngChunkTypes(drawing.png)
	if (!types.length) failures.push('renderPng did not emit a readable PNG stream')
	if (types[types.length - 1] !== 'IEND') failures.push(`rendered PNG ends at "${types[types.length - 1] ?? 'nothing'}", not IEND - the stream is truncated`)
	if (!types.includes('IDAT')) failures.push('rendered PNG carries no IDAT chunk - a valid file with nothing drawn')
	if (be32(drawing.png, 16) !== drawing.width || be32(drawing.png, 20) !== drawing.height) {
		failures.push(`renderPng reports ${drawing.width}x${drawing.height} but its IHDR encodes ${be32(drawing.png, 16)}x${be32(drawing.png, 20)}`)
	}
	if (drawing.rgba.length !== drawing.width * drawing.height * 4) {
		failures.push(`the pixel buffer is ${drawing.rgba.length} bytes for a ${drawing.width}x${drawing.height} image`)
	}
	const colours = new Set<string>()
	for (let i = 0; i < drawing.rgba.length; i += 4) {
		if (drawing.rgba[i + 3]) colours.add(`${drawing.rgba[i]},${drawing.rgba[i + 1]},${drawing.rgba[i + 2]}`)
	}
	if (colours.size < 3) failures.push(`the drawing holds ${colours.size} distinct colour(s); a plan with walls, rooms and doors cannot be that flat`)

	const sheets = renderContactSheet([renderPng(floor, { scale: 4 }), renderPng(floor, { scale: 4 })], ['A', 'B'])
	if (pngChunkTypes(sheets.png).length === 0) failures.push('the contact sheet is not a readable PNG')
	if (sheets.width <= renderPng(floor, { scale: 4 }).width) failures.push(`a two-panel sheet is ${sheets.width}px wide - it did not compose the panels side by side`)

	const ascii = renderAscii(floor, bundle.world, { findings: [] })
	if (!ascii.includes('legend:')) failures.push('the ascii plan has no legend, so its glyphs cannot be read back')
	if (floor.portals.length && !ascii.includes('P')) failures.push('the floor has portals but the ascii plan never draws one')

	// A storey with no street frontage is only reachable through its core, so its arrival cell must be
	// a boarding cell - the branch no single-storey fixture ever takes.
	const stacked = loadWorld(stack.planPath).world
	const upper = stacked.floors.find(candidate => !candidate.isStreetFloor)
	const arrival = upper ? entryCell(stacked, upper) : null
	if (!upper || !arrival) failures.push(`${DRIFT_FIXTURE}: no arrival cell could be derived for the upper storey`)
	else {
		const boarding = new Set(upper.portals.flatMap(portal => portal.spotCells.map(cell => `${cell.x},${cell.y}`)))
		if (!boarding.has(`${arrival.x},${arrival.y}`)) failures.push(`arrival on the upper storey landed at (${arrival.x},${arrival.y}), off every portal boarding cell`)
	}

	// The report artefact has to agree with the model cell by cell. A SVG that renders one rect per
	// tile, ignores the room typing, or crops the wrong extent would still be a valid drawing.
	const svg = renderSvg(floor, { scale: 4 })
	const rects = (svg.match(/<rect\b/g) ?? []).length
	if (rects !== 1 + floor.cols * floor.rows) failures.push(`renderSvg emitted ${rects} rects for a ${floor.cols}x${floor.rows} floor, expected one per tile plus the background`)
	if (floor.rooms.some(room => !room.isCorridor && !room.isStreet) && svg === renderSvg(floor, { scale: 4, rooms: false })) failures.push('renderSvg draws an identical picture with room typing off, so the type never reaches the report')
	const crop = renderSvg(floor, { scale: 4, zoom: { x0: 0, y0: 0, x1: 9, y1: 9 } })
	if ((crop.match(/<rect\b/g) ?? []).length !== 101) failures.push('a 10x10 zoom window did not emit 100 tiles, so the crop misrepresents its own extent')
	const portalCell = floor.portals[0]?.cells[0]
	if (portalCell && !renderSvg(floor, { scale: 4, markCells: [portalCell] }).includes('#e74c3c')) failures.push('markCells produced no overlay colour, so a finding counterexample would not appear on the plan')
	return failures
}

/**
 * The KPI vector is the only judgeable surface the reports publish: a value with no band cannot be
 * called good or bad, and a band with no source is an opinion wearing a number. Nothing previously
 * checked either, so a malformed row would degrade every report silently and still print green.
 */
function runVectorChecks(runs: readonly FixtureRun[]): string[] {
	const failures: string[] = []
	for (const run of runs) {
		const bundle = loadWorld(run.planPath)
		const groups = [...bundle.world.floors.map(floor => ({ label: floor.id, kpis: floorKpis(bundle.world, floor) })), { label: 'building', kpis: buildingKpis(bundle.world) }]
		const vector = groups.flatMap(group => group.kpis)
		if (vector.length < 10) failures.push(`${run.fixture.id}: only ${vector.length} KPIs published; the vector looks incomplete`)
		for (const kpi of vector) {
			const where = `${run.fixture.id}/${kpi.key || '(blank key)'}`
			if (!kpi.key) failures.push(`${where}: empty key`)
			if (!kpi.label) failures.push(`${where}: empty label`)
			if (!kpi.unit) failures.push(`${where}: empty unit`)
			if (!kpi.band.trim()) failures.push(`${where}: no band, so the value is not judgeable`)
			if (!kpi.bandSource.trim()) failures.push(`${where}: no band source, so the band is an opinion`)
			if (!Number.isFinite(kpi.value)) failures.push(`${where}: value is ${kpi.value}, not a finite number`)
			if (kpi.direction !== 'up' && kpi.direction !== 'down' && kpi.direction !== 'band') failures.push(`${where}: direction "${kpi.direction}" is outside the vocabulary`)
			if (kpi.unit === '%' && (kpi.value < 0 || kpi.value > 100)) failures.push(`${where}: a percentage reading ${kpi.value}`)
		}
		// Some rows are computed over a sample set the vector also publishes. An empty sample is not a
		// measurement: scored, it either fails a gate no geometry could pass or - worse - passes a
		// safety gate on absence of evidence. Each denominator row must therefore govern its rows.
		const SAMPLES: { key: string; governs: string[] }[] = [
			{ key: 'circulationWidthSamples', governs: ['corridorMinWidth', 'corridorP50Width', 'singleFileShare', 'deadEnds'] },
			{ key: 'programmeRoomSamples', governs: ['roomsBeyondDaylight', 'worstFreeRun'] },
		]
		for (const group of groups) {
			const byKey = new Map(group.kpis.map(kpi => [kpi.key, kpi]))
			for (const sample of SAMPLES) {
				const denominator = byKey.get(sample.key)
				// A missing denominator would make the whole rule silently inert, so it is a failure.
				if (!denominator && group.label !== 'building') failures.push(`${run.fixture.id}/${group.label}/${sample.key}: the vector publishes no sample count, so its governed rows cannot be audited`)
				if (!denominator || denominator.value > 0) continue
				for (const key of sample.governs) {
					const row = byKey.get(key)
					if (row && (row.direction !== 'band' || row.gate)) {
						failures.push(`${run.fixture.id}/${group.label}/${key}: direction "${row.direction}" and gate=${row.gate} on ${sample.key} = 0; an unmeasurable row must be band, ungated`)
					}
				}
			}
		}
		// A key appears once per storey by design, so uniqueness is a within-group property.
		for (const group of groups) {
			const keys = new Set<string>()
			for (const kpi of group.kpis) {
				if (keys.has(kpi.key)) failures.push(`${run.fixture.id}/${group.label}/${kpi.key}: duplicate key inside one vector`)
				keys.add(kpi.key)
			}
		}
	}

	// The regression reader the loop now reports through: nothing may regress against itself, and a
	// knowingly broken plan must be worse on something. An empty result either way means the direction
	// logic is inert, which is worse than no reader at all because the loop would then look clean.
	const controlWorld = loadWorld(runs.find(run => run.fixture.polarity === 'good')?.planPath ?? runs[0].planPath).world
	if (regressions(controlWorld, controlWorld).length) failures.push('a world regressed against itself')
	const brokenRun = runs.find(run => run.fixture.id === BLOCKED_FIXTURE)
	if (brokenRun) {
		const worse = regressions(controlWorld, loadWorld(brokenRun.planPath).world)
		if (!worse.length) failures.push(`${BLOCKED_FIXTURE} is worse than the control on no measured metric - the direction comparison is inert`)
		if (worse.some(row => Math.abs(row.delta) < 1e-9)) failures.push('a reported regression carries a zero delta')
		if (!worse.some(row => row.gate)) failures.push('no gate metric regressed on a plan with unreachable rooms')
	}
	return failures
}

/**
 * The money stage. `--economy` ranks plans on what the crowd banks, and until this stage existed nothing
 * proved the tool *can* bank: the tariff and the shipped content drifted apart once without anyone
 * noticing (loop 58 found a library carrying no rate tag at all), and a ranking whose money columns are
 * all zero still prints a winner.
 *
 * Two readings of one plan - the authored income fixture, drawn into a copy of the shipped workspace -
 * that differ only in whether the fixtures it places are priced: the control swaps every billable
 * fixture for a sofa, which the crowd still uses and the tariff still ignores. A zero bank in the
 * control therefore means the tariff, not a broken harness.
 */
const STORE_FILE = path.join(ROOT, 'src/blueprint-editor/data/blueprint-data.json')
const INCOME_PLAN = path.join(HERE, 'lobby', 'services-probe.txt')
/** One authored day at the engine's clock, so a reading is a day and not a fragment of one. */
const ECONOMY_TICKS = 18_000

function economyPayload(name: string, unbilled: boolean): string {
	const file = path.join(WORK, `${name}.json`)
	fs.writeFileSync(file, fs.readFileSync(STORE_FILE, 'utf8'))
	if (buildLobby(file, INCOME_PLAN, true).fixtures <= 0) throw new Error(`the economy probe wrote no fixtures into ${name}`)
	if (!unbilled) return file
	const payload = JSON.parse(fs.readFileSync(file, 'utf8')) as {
		originAssets: { id: string; tags?: string[] }[]
		layout: { floors: { objects: { type: string }[] }[] }
	}
	const bills = (type: string) =>
		(payload.originAssets.find(asset => asset.id === type)?.tags ?? []).some(
			tag => tag in TAKING_RATES_CENTS && !tag.startsWith('post:'),
		)
	for (const floor of payload.layout.floors) {
		for (const object of floor.objects) if (bills(object.type)) object.type = 'sofa-1'
	}
	fs.writeFileSync(file, `${JSON.stringify(payload, null, 1)}\n`)
	return file
}

function runEconomyChecks(): string[] {
	const failures: string[] = []
	const options = { ticks: ECONOMY_TICKS, agents: 20, arrivals: true, arrivalsPerDay: 150 }
	const earning = measureTakings(economyPayload('economy-earning', false), options)
	const unbilled = measureTakings(economyPayload('economy-unbilled', true), options)

	// Both branches have to be seen. An empty bank in the control only means something when the same
	// crowd was still served, and a full one in the probe only means something against that control.
	if (earning.completed <= 0 || earning.served <= 0) {
		failures.push(`the income fixture served nobody (${earning.started} started, ${earning.completed} completed, ${earning.served} billed) - the money stage is measuring a harness, not a plan`)
	} else if (earning.bankCents <= 0) {
		failures.push(`${earning.served} billed services at priced fixtures banked ${earning.bankCents} - the tariff and the shipped content have drifted apart`)
	}
	// `served` is the ledger's count of billed services, so the control's zero there is the claim itself.
	// What it has to prove is that the crowd still worked the room - `completed` - while banking nothing;
	// otherwise an empty bank would only show that nobody got anywhere.
	if (unbilled.completed <= 0) {
		failures.push(`the unpriced control completed no service (${unbilled.started} started), so its empty bank proves nothing about the tariff`)
	} else if (unbilled.bankCents > 0 || unbilled.served > 0) {
		failures.push(`fixtures with no tariff tag banked ${unbilled.bankCents} across ${unbilled.served} billed services - "bills nothing" is no longer something the control can show`)
	}
	return failures
}

export function runSelfTest(): number {
	const runs = runFixtures()
	const failures: string[] = []

	const width = Math.max(...runs.map(run => run.fixture.id.length))
	const lines: string[] = ['# Failure-library selftest', '', `${'fixture'.padEnd(width)}  polarity  verdict   findings`, '-'.repeat(width + 46)]
	for (const run of runs) {
		const { fixture, report, ids } = run
		lines.push(`${fixture.id.padEnd(width)}  ${fixture.polarity.padEnd(8)}  ${report.verdict.toUpperCase().padEnd(7)}  ${[...ids].sort().join(' ') || '-'}`)
		if (run.missing.length) failures.push(`${fixture.id}: expected findings did NOT fire -> ${run.missing.join(', ')}`)
		if (run.unexpected.length) failures.push(`${fixture.id}: control fixture produced findings -> ${run.unexpected.join(', ')}`)
	}

	fs.mkdirSync(path.dirname(LIBRARY), { recursive: true })
	fs.writeFileSync(LIBRARY, `${formatLibrary(runs)}\n`)
	lines.push('', `failure library written: ${path.relative(ROOT, LIBRARY).split(path.sep).join('/')}`)
	lines.push(`fixture plans, PNGs and ASCII: ${path.relative(ROOT, WORK).split(path.sep).join('/')}`)

	const repair = runRepairChecks(runs)
	const comparison = runCompareChecks(runs)
	const vertical = runVerticalChecks(runs)
	const render = runRenderChecks(runs)
	const vector = runVectorChecks(runs)
	const economy = runEconomyChecks()
	failures.push(...repair, ...comparison, ...vertical, ...render, ...vector, ...economy)
	lines.push('')
	lines.push(`repair stage:   ${repair.length ? 'FAILED' : 'ok'} - a no-op earns nothing, cleared/still-open/introduced and the metric deltas are reproducible, and a rung may not understate its own operations`)
	lines.push(`compare stage:  ${comparison.length ? 'FAILED' : 'ok'} - a critical finding disqualifies an option, a variant of one is collapsed instead of ranked, and every ranked column - geometry and money alike - is measured on every option`)
	lines.push(`section stage:  ${vertical.length ? 'FAILED' : 'ok'} - drift is blamed on the storey that moved, and only that storey`)
	lines.push(`render stage:   ${render.length ? 'FAILED' : 'ok'} - the picture is a real, non-blank, fully-composed image and an upper storey is entered through its core`)
	lines.push(`vector stage:   ${vector.length ? 'FAILED' : 'ok'} - every published KPI is judgeable: a band, a band source, a finite value, a legal direction, unique keys per storey`)
	lines.push(`economy stage:  ${economy.length ? 'FAILED' : 'ok'} - a tagged fixture banks money to a served crowd, and an untagged one banks nothing to the same crowd`)

	if (failures.length) {
		lines.push('', `## FAILED (${failures.length})`)
		for (const failure of failures) lines.push(`- ${failure}`)
	} else {
		lines.push('', `## PASSED - ${runs.length} fixtures, every bad plan fired its findings, the control stayed clean`)
	}
	console.info(lines.join('\n'))
	return failures.length ? 1 : 0
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
	process.exitCode = runSelfTest()
}
